name: vagrant

on: [push]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: lint
        run: make lint

      - name: Cache Vagrant boxes
        uses: actions/cache@v3
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os}}-vagrant-

      - name: vagrant version
        run: vagrant --version

      - name: run tests
        run: make test
